FROM node:22-bookworm-slim

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install required system packages
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    make \
    g++ \
    libcairo2 \
    libcairo2-dev \
    libpango-1.0-0 \
    libpango1.0-dev \
    libjpeg62-turbo \
    libjpeg62-turbo-dev \
    libgif7 \
    libgif-dev \
    librsvg2-2 \
    librsvg2-dev \
    pkg-config \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Clone latest project
RUN git clone https://github.com/memori-ai/mcp-sharepoint.git .

# Remove lock file to avoid incompatible dependency resolution
RUN rm -f package-lock.json

# Install dependencies
RUN npm install

# Downgrade pdf-parse to a stable version
RUN npm install pdf-parse@2.3.12 --save-exact

# Clean npm cache
RUN npm cache clean --force

# Install mcp-proxy — bridges stdio to SSE/HTTP, spawns a fresh child
# process per session (fixes the "Already connected" crash supergateway had)
RUN npm install -g mcp-proxy

# Write the credential-injecting wrapper directly into the image (base64
# encoded to avoid Dockerfile quoting issues). It hides tenantId/clientId/
# clientSecret/siteId/driveId from the tool schema Claude sees, and injects
# the real values (from env vars set in Easypanel) on every tool call.
RUN echo IyEvdXNyL2Jpbi9lbnYgbm9kZQovKioKICogd3JhcHBlci5janMKICoKICogU2l0cyBiZXR3ZWVuIG1jcC1wcm94eSAodGhlIFNTRS9IVFRQIGJyaWRnZSkgYW5kIHRoZSByZWFsCiAqIG1jcC1zaGFyZXBvaW50IHByb2Nlc3MgKHN0ZGlvIEpTT04tUlBDKS4KICoKICogV2hhdCBpdCBkb2VzOgogKiAgMS4gU3Bhd25zICJub2RlIHNyYy9pbmRleC5qcyIgKHRoZSByZWFsIG1jcC1zaGFyZXBvaW50IHNlcnZlcikgYXMgYSBjaGlsZC4KICogIDIuIEludGVyY2VwdHMgdGhlICJ0b29scy9saXN0IiByZXNwb25zZSBhbmQgcmVtb3ZlcyB0aGUgY3JlZGVudGlhbAogKiAgICAgZmllbGRzICh0ZW5hbnRJZCwgY2xpZW50SWQsIGNsaWVudFNlY3JldCwgc2l0ZUlkLCBkcml2ZUlkKSBmcm9tCiAqICAgICBlYWNoIHRvb2wncyBpbnB1dCBzY2hlbWEsIHNvIENsYXVkZSBuZXZlciBzZWVzIG9yIGFza3MgZm9yIHRoZW0uCiAqICAzLiBJbnRlcmNlcHRzIGV2ZXJ5ICJ0b29scy9jYWxsIiByZXF1ZXN0IGFuZCBpbmplY3RzIHRoZSByZWFsCiAqICAgICBjcmVkZW50aWFsIHZhbHVlcyAocmVhZCBmcm9tIGVudmlyb25tZW50IHZhcmlhYmxlcykgaW50byB0aGUKICogICAgIGFyZ3VtZW50cyBiZWZvcmUgZm9yd2FyZGluZyB0byB0aGUgY2hpbGQgcHJvY2Vzcy4KICogIDQuIEV2ZXJ5dGhpbmcgZWxzZSBpcyBwYXNzZWQgdGhyb3VnaCB1bnRvdWNoZWQuCiAqCiAqIFJlcXVpcmVkIGVudmlyb25tZW50IHZhcmlhYmxlcyAoc2V0IHRoZXNlIGluIEVhc3lwYW5lbCdzCiAqIEVudmlyb25tZW50IFZhcmlhYmxlcyBwYW5lbCBmb3IgdGhpcyBzZXJ2aWNlIOKAlCBOT1QgaW4gdGhlCiAqIERvY2tlcmZpbGUsIGFuZCBOT1QgaW4gY2hhdCk6CiAqICAgU1BfVEVOQU5UX0lECiAqICAgU1BfQ0xJRU5UX0lECiAqICAgU1BfQ0xJRU5UX1NFQ1JFVAogKiAgIFNQX1NJVEVfSUQKICogICBTUF9EUklWRV9JRAogKi8KCmNvbnN0IHsgc3Bhd24gfSA9IHJlcXVpcmUoImNoaWxkX3Byb2Nlc3MiKTsKY29uc3QgcmVhZGxpbmUgPSByZXF1aXJlKCJyZWFkbGluZSIpOwoKY29uc3QgQ1JFRF9GSUVMRFMgPSBbInRlbmFudElkIiwgImNsaWVudElkIiwgImNsaWVudFNlY3JldCIsICJzaXRlSWQiLCAiZHJpdmVJZCJdOwoKY29uc3QgQ1JFRFMgPSB7CiAgdGVuYW50SWQ6IHByb2Nlc3MuZW52LlNQX1RFTkFOVF9JRCwKICBjbGllbnRJZDogcHJvY2Vzcy5lbnYuU1BfQ0xJRU5UX0lELAogIGNsaWVudFNlY3JldDogcHJvY2Vzcy5lbnYuU1BfQ0xJRU5UX1NFQ1JFVCwKICBzaXRlSWQ6IHByb2Nlc3MuZW52LlNQX1NJVEVfSUQsCiAgZHJpdmVJZDogcHJvY2Vzcy5lbnYuU1BfRFJJVkVfSUQsCn07Cgpmb3IgKGNvbnN0IFtrZXksIHZhbF0gb2YgT2JqZWN0LmVudHJpZXMoQ1JFRFMpKSB7CiAgaWYgKCF2YWwpIHsKICAgIHByb2Nlc3Muc3RkZXJyLndyaXRlKAogICAgICBgW3dyYXBwZXJdIFdBUk5JTkc6IG1pc3NpbmcgZW52IHZhciBmb3IgIiR7a2V5fSIg4oCUIHRvb2wgY2FsbHMgbmVlZGluZyBpdCB3aWxsIGZhaWwuXG5gCiAgICApOwogIH0KfQoKLy8gU3Bhd24gdGhlIHJlYWwgbWNwLXNoYXJlcG9pbnQgc2VydmVyCmNvbnN0IGNoaWxkID0gc3Bhd24oIm5vZGUiLCBbInNyYy9pbmRleC5qcyJdLCB7CiAgc3RkaW86IFsicGlwZSIsICJwaXBlIiwgImluaGVyaXQiXSwgLy8gaW5oZXJpdCBzdGRlcnIgc28gaXRzIGxvZ3Mgc3RpbGwgc2hvdyBpbiBFYXN5cGFuZWwKfSk7CgovLyAtLS0gT3V0Z29pbmc6IHBhcmVudCAobWNwLXByb3h5KSAtPiB3cmFwcGVyIC0+IGNoaWxkIC0tLQpjb25zdCBwYXJlbnRSZWFkZXIgPSByZWFkbGluZS5jcmVhdGVJbnRlcmZhY2UoeyBpbnB1dDogcHJvY2Vzcy5zdGRpbiB9KTsKCnBhcmVudFJlYWRlci5vbigibGluZSIsIChsaW5lKSA9PiB7CiAgaWYgKCFsaW5lLnRyaW0oKSkgcmV0dXJuOwogIGxldCBtc2c7CiAgdHJ5IHsKICAgIG1zZyA9IEpTT04ucGFyc2UobGluZSk7CiAgfSBjYXRjaCB7CiAgICAvLyBOb3QgSlNPTiwganVzdCBmb3J3YXJkIHJhdwogICAgY2hpbGQuc3RkaW4ud3JpdGUobGluZSArICJcbiIpOwogICAgcmV0dXJuOwogIH0KCiAgLy8gSW5qZWN0IGNyZWRlbnRpYWxzIGludG8gZXZlcnkgdG9vbHMvY2FsbCByZXF1ZXN0CiAgaWYgKG1zZy5tZXRob2QgPT09ICJ0b29scy9jYWxsIiAmJiBtc2cucGFyYW1zICYmIG1zZy5wYXJhbXMuYXJndW1lbnRzKSB7CiAgICBtc2cucGFyYW1zLmFyZ3VtZW50cyA9IHsgLi4ubXNnLnBhcmFtcy5hcmd1bWVudHMsIC4uLkNSRURTIH07CiAgfQoKICBjaGlsZC5zdGRpbi53cml0ZShKU09OLnN0cmluZ2lmeShtc2cpICsgIlxuIik7Cn0pOwoKLy8gLS0tIEluY29taW5nOiBjaGlsZCAtPiB3cmFwcGVyIC0+IHBhcmVudCAobWNwLXByb3h5KSAtLS0KY29uc3QgY2hpbGRSZWFkZXIgPSByZWFkbGluZS5jcmVhdGVJbnRlcmZhY2UoeyBpbnB1dDogY2hpbGQuc3Rkb3V0IH0pOwoKY2hpbGRSZWFkZXIub24oImxpbmUiLCAobGluZSkgPT4gewogIGlmICghbGluZS50cmltKCkpIHJldHVybjsKICBsZXQgbXNnOwogIHRyeSB7CiAgICBtc2cgPSBKU09OLnBhcnNlKGxpbmUpOwogIH0gY2F0Y2ggewogICAgcHJvY2Vzcy5zdGRvdXQud3JpdGUobGluZSArICJcbiIpOwogICAgcmV0dXJuOwogIH0KCiAgLy8gU3RyaXAgY3JlZGVudGlhbCBmaWVsZHMgb3V0IG9mIHRoZSB0b29scy9saXN0IHJlc3BvbnNlIHNjaGVtYQogIGlmIChtc2cucmVzdWx0ICYmIEFycmF5LmlzQXJyYXkobXNnLnJlc3VsdC50b29scykpIHsKICAgIGZvciAoY29uc3QgdG9vbCBvZiBtc2cucmVzdWx0LnRvb2xzKSB7CiAgICAgIGlmICh0b29sLmlucHV0U2NoZW1hICYmIHRvb2wuaW5wdXRTY2hlbWEucHJvcGVydGllcykgewogICAgICAgIGZvciAoY29uc3QgZmllbGQgb2YgQ1JFRF9GSUVMRFMpIHsKICAgICAgICAgIGRlbGV0ZSB0b29sLmlucHV0U2NoZW1hLnByb3BlcnRpZXNbZmllbGRdOwogICAgICAgIH0KICAgICAgICBpZiAoQXJyYXkuaXNBcnJheSh0b29sLmlucHV0U2NoZW1hLnJlcXVpcmVkKSkgewogICAgICAgICAgdG9vbC5pbnB1dFNjaGVtYS5yZXF1aXJlZCA9IHRvb2wuaW5wdXRTY2hlbWEucmVxdWlyZWQuZmlsdGVyKAogICAgICAgICAgICAoZikgPT4gIUNSRURfRklFTERTLmluY2x1ZGVzKGYpCiAgICAgICAgICApOwogICAgICAgIH0KICAgICAgfQogICAgfQogIH0KCiAgcHJvY2Vzcy5zdGRvdXQud3JpdGUoSlNPTi5zdHJpbmdpZnkobXNnKSArICJcbiIpOwp9KTsKCmNoaWxkLm9uKCJleGl0IiwgKGNvZGUpID0+IHsKICBwcm9jZXNzLnN0ZGVyci53cml0ZShgW3dyYXBwZXJdIGNoaWxkIGV4aXRlZCB3aXRoIGNvZGUgJHtjb2RlfVxuYCk7CiAgcHJvY2Vzcy5leGl0KGNvZGUgPz8gMSk7Cn0pOwoKcHJvY2Vzcy5vbigiU0lHVEVSTSIsICgpID0+IGNoaWxkLmtpbGwoIlNJR1RFUk0iKSk7CnByb2Nlc3Mub24oIlNJR0lOVCIsICgpID0+IGNoaWxkLmtpbGwoIlNJR0lOVCIpKTsK | base64 -d > /app/wrapper.cjs

EXPOSE 8000

# mcp-proxy launches the wrapper instead of src/index.js directly.
# The wrapper spawns src/index.js itself and proxies stdio to/from it.
CMD ["mcp-proxy", "--port", "8000", "--sseEndpoint", "/sse", "--", "node", "wrapper.cjs"]
